apiVersion: v1
kind: Service
metadata:
  name: {{ include "mesh-test.fullname" . }}
  labels:
    {{- include "mesh-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http-server
  selector:
    {{- include "mesh-test.selectorLabels" . | nindent 4 }}
